apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.appName }}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx

    # rate limit

    nginx.ingress.kubernetes.io/limit-rps: "10" # 10 requests per second
    nginx.ingress.kubernetes.io/limit-connections: "5" # 5 concurrent connections
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "2" # 2x the normal rate burst
    nginx.ingress.kubernetes.io/limit-rate-status-code: "429" # 429 status code when rate limit is exceeded
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.appName }}
                port:
                  number: {{ .Values.servicePort }}